definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  models.LLMRequest:
    properties:
      content:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/stage-api/qa:
    post:
      consumes:
      - application/json
      parameters:
      - description: Question to be answered
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/models.LLMRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Answer a question
      tags:
      - QA
  /api/stage-api/tags:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get multiple article tags
swagger: "2.0"
